/*
 * Operaciones.java
 *
 * Generated with Matisse Schema Definition Language 9.1.10
 * Generation date: Wed Apr 04 13:39:47 2018
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package banco;

import com.matisse.reflect.*;

/**
 * <code>Operaciones</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Operaciones extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.10
     * Generation Date: Wed Apr 04 13:39:47 2018
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Operaciones</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("banco.Operaciones"));

    /**
     * Gets the <code>Operaciones</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Operaciones(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Operaciones(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Operaciones.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Operaciones.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Operaciones.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Operaciones.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'Id_Operacion' */

    /** Attribute <code>Id_Operacion</code> cache ID */
    private static int id_OperacionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("Id_Operacion",CID));

    /**
     * Gets the <code>Id_Operacion</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getId_OperacionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(id_OperacionCID);
    }


    /**
     * Gets the <code>Id_Operacion</code> attribute value.
     * @return the value
     *
     * @see #setId_Operacion
     * @see #removeId_Operacion
     */
    public final int getId_Operacion() {
        return getInteger(getId_OperacionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>Id_Operacion</code> attribute value.
     * @param val the new value
     *
     * @see #getId_Operacion
     * @see #removeId_Operacion
     */
    public final void setId_Operacion(int val) {
        setInteger(getId_OperacionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>Id_Operacion</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getId_Operacion
     * @see #setId_Operacion
     */
    public final void removeId_Operacion() {
        removeValue(getId_OperacionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getId_Operacion
     * @see #setId_Operacion
     */
    public final boolean isId_OperacionDefaultValue() {
        return isDefaultValue(getId_OperacionAttribute(getMtDatabase()));
    }


    /* Attribute 'Fecha_Hora' */

    /** Attribute <code>Fecha_Hora</code> cache ID */
    private static int fecha_HoraCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("Fecha_Hora",CID));

    /**
     * Gets the <code>Fecha_Hora</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getFecha_HoraAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(fecha_HoraCID);
    }


    /**
     * Gets the <code>Fecha_Hora</code> attribute value.
     * @return the value
     *
     * @see #setFecha_Hora
     * @see #removeFecha_Hora
     */
    public final String getFecha_Hora() {
        return getString(getFecha_HoraAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>Fecha_Hora</code> attribute value.
     * @param val the new value
     *
     * @see #getFecha_Hora
     * @see #removeFecha_Hora
     */
    public final void setFecha_Hora(String val) {
        setString(getFecha_HoraAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>Fecha_Hora</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getFecha_Hora
     * @see #setFecha_Hora
     */
    public final void removeFecha_Hora() {
        removeValue(getFecha_HoraAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getFecha_Hora
     * @see #setFecha_Hora
     */
    public final boolean isFecha_HoraDefaultValue() {
        return isDefaultValue(getFecha_HoraAttribute(getMtDatabase()));
    }


    /* Attribute 'Numero_Cuenta' */

    /** Attribute <code>Numero_Cuenta</code> cache ID */
    private static int numero_CuentaCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("Numero_Cuenta",CID));

    /**
     * Gets the <code>Numero_Cuenta</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNumero_CuentaAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(numero_CuentaCID);
    }


    /**
     * Gets the <code>Numero_Cuenta</code> attribute value.
     * @return the value
     *
     * @see #setNumero_Cuenta
     * @see #removeNumero_Cuenta
     */
    public final String getNumero_Cuenta() {
        return getString(getNumero_CuentaAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>Numero_Cuenta</code> attribute value.
     * @param val the new value
     *
     * @see #getNumero_Cuenta
     * @see #removeNumero_Cuenta
     */
    public final void setNumero_Cuenta(String val) {
        setString(getNumero_CuentaAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>Numero_Cuenta</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNumero_Cuenta
     * @see #setNumero_Cuenta
     */
    public final void removeNumero_Cuenta() {
        removeValue(getNumero_CuentaAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNumero_Cuenta
     * @see #setNumero_Cuenta
     */
    public final boolean isNumero_CuentaDefaultValue() {
        return isDefaultValue(getNumero_CuentaAttribute(getMtDatabase()));
    }


    /* Attribute 'Tipo_Operacion' */

    /** Attribute <code>Tipo_Operacion</code> cache ID */
    private static int tipo_OperacionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("Tipo_Operacion",CID));

    /**
     * Gets the <code>Tipo_Operacion</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getTipo_OperacionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(tipo_OperacionCID);
    }


    /**
     * Gets the <code>Tipo_Operacion</code> attribute value.
     * @return the value
     *
     * @see #setTipo_Operacion
     * @see #removeTipo_Operacion
     */
    public final String getTipo_Operacion() {
        return getString(getTipo_OperacionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>Tipo_Operacion</code> attribute value.
     * @param val the new value
     *
     * @see #getTipo_Operacion
     * @see #removeTipo_Operacion
     */
    public final void setTipo_Operacion(String val) {
        setString(getTipo_OperacionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>Tipo_Operacion</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getTipo_Operacion
     * @see #setTipo_Operacion
     */
    public final void removeTipo_Operacion() {
        removeValue(getTipo_OperacionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getTipo_Operacion
     * @see #setTipo_Operacion
     */
    public final boolean isTipo_OperacionDefaultValue() {
        return isDefaultValue(getTipo_OperacionAttribute(getMtDatabase()));
    }


    /* Attribute 'Cantidad' */

    /** Attribute <code>Cantidad</code> cache ID */
    private static int cantidadCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("Cantidad",CID));

    /**
     * Gets the <code>Cantidad</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getCantidadAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(cantidadCID);
    }


    /**
     * Gets the <code>Cantidad</code> attribute value.
     * @return the value
     *
     * @see #setCantidad
     * @see #removeCantidad
     */
    public final int getCantidad() {
        return getInteger(getCantidadAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>Cantidad</code> attribute value.
     * @param val the new value
     *
     * @see #getCantidad
     * @see #removeCantidad
     */
    public final void setCantidad(int val) {
        setInteger(getCantidadAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>Cantidad</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getCantidad
     * @see #setCantidad
     */
    public final void removeCantidad() {
        removeValue(getCantidadAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getCantidad
     * @see #setCantidad
     */
    public final boolean isCantidadDefaultValue() {
        return isDefaultValue(getCantidadAttribute(getMtDatabase()));
    }


    /*
     * Index access methods
     */

    /* Index 'prim2' */

    /** Index <code>prim2</code> cache ID */
    private static int prim2IndexCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtIndex.Loader("banco.prim2"));

    /**
     * Gets the <code>prim2</code> index descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return an index descriptor object
     */
    public static com.matisse.reflect.MtIndex getPrim2Index(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtIndex)db.getCachedObject(prim2IndexCID);
    }

    /**
     * Finds one <code>Operaciones</code> object in index <code>prim2</code>.
     * @param db a database
     * @param id_Operacion search parameter
     * @return the matching <code>Operaciones</code> object or <code>null</code> if none was found
     */
    public static Operaciones lookupPrim2(com.matisse.MtDatabase db, int id_Operacion) {
        return (Operaciones)getPrim2Index(db).lookup(new Object[] {new Integer(id_Operacion)}, getClass(db));
    }

    /**
     * Finds <code>Operaciones</code> objects in index <code>prim2</code>.
     * @param db a database
     * @param id_Operacion search parameter
     * @return the matching <code>Operaciones</code> objects or an empty array if none was found
     */
    public static Operaciones[] lookupObjectsPrim2(com.matisse.MtDatabase db, int id_Operacion) {
        return (Operaciones[])getPrim2Index(db).lookupObjects(new Object[] {new Integer(id_Operacion)}, getClass(db), Operaciones.class);
    }

    /**
     * Opens an iterator on index <code>prim2</code> for class <code>Operaciones</code>.
     * Each indexed attribute has a pair of "from" and "to" parameters which
     * define the search range for that attribute.  With strings, you may use
     * <code>null</code> to start "from" at the beginning or extend "to" to the end.
     * @param <E> a MtObject class     * @param db a database
     * @param fromId_Operacion search parameter
     * @param toId_Operacion search parameter
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> prim2Iterator(com.matisse.MtDatabase db, int fromId_Operacion, int toId_Operacion) {
        return getPrim2Index(db).<E>iterator(new Object[] {new Integer(fromId_Operacion)}, new Object[] {new Integer(toId_Operacion)}, getClass(db), com.matisse.reflect.MtIndex.DIRECT, com.matisse.MtDatabase.MAX_PREFETCHING, Operaciones.class);
    }

    /**
     * Opens an iterator on index <code>prim2</code> for class <code>Operaciones</code>. 
     * Each indexed attribute has a pair of "from" and "to" parameters which
     * define the search range for that attribute.  With strings, you may use
     * <code>null</code> to start "from" at the beginning or extend "to" to the end.
     * @param <E> a MtObject class     * @param db a database
     * @param fromId_Operacion search parameter
     * @param toId_Operacion search parameter
     * @param filterClass a subclass; use <code>null</code> not to restrict iterator to a subclass
     * @param direction MtIndex.DIRECT or MtIndex.REVERSE
     * @param numObjPerBuffer maximum number of objects to be retrieved in each request to server
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> prim2Iterator(com.matisse.MtDatabase db, int fromId_Operacion, int toId_Operacion, com.matisse.reflect.MtClass filterClass, int direction, int numObjPerBuffer) {
        return getPrim2Index(db).iterator(new Object[] {new Integer(fromId_Operacion)}, new Object[] {new Integer(toId_Operacion)}, filterClass, direction, numObjPerBuffer, Operaciones.class);
    }

    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Operaciones(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Operaciones]";
    }
}
